### ISSUE TITLE
where to get `imageNet.h`, `loadImage.h` and `cudaFont.h`

### ISSUE THREAD

**Issue by IvyGongoogle** [ctuning/ck-tensorrt#15]
hello, I like your this work, but where to get `imageNet.h`, `loadImage.h` and `cudaFont.h`?
can you give some advises?
thank you very much~

**Comment by psyhtest** [comment]
Hi @IvyGongoogle, thanks for your interest! Could you please provide more details as to how you are trying to use CK-TensorRT?

These files are part of the [Jetson Inference](https://github.com/dusty-nv/jetson-inference) library, and should be installed automatically:
```
anton@tegra-ubuntu:~/CK_TOOLS/lib-jetson-inference-nvidia-trunk-gcc-5.4.1-compiler.cuda-8.0.72-linux-64$ find include -name loadImage.h
include/loadImage.h
anton@tegra-ubuntu:~/CK_TOOLS/lib-jetson-inference-nvidia-trunk-gcc-5.4.1-compiler.cuda-8.0.72-linux-64$ find include -name imageNet.h
include/imageNet.h
anton@tegra-ubuntu:~/CK_TOOLS/lib-jetson-inference-nvidia-trunk-gcc-5.4.1-compiler.cuda-8.0.72-linux-64$ find include -name cudaFont.h
include/cudaFont.h
```
or semi-manually:
```
$ ck install package --tags=nvidia,lib,jetson-inference
```

Note that we last checked this package with TensorRT 2.1.2 on TX1 and with TensorRT 3.0.4 on GTX1080.
